### ISSUE TITLE
Plugin crashes when version field is not available.

### ISSUE THREAD

**Issue by mashhurs** [logstash-plugins/logstash-codec-cef#103]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
4. How was the Logstash Plugin installed

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```
{"level":"ERROR","loggerName":"logstash.codecs.cef","timeMillis":1721266426115,"thread":"nioEventLoopGroup-8-1","logEvent":{"message":"Failed to decode CEF payload. Generating failure event with payload in message field.","exception":{"metaClass":{"metaClass":{"exception":"NoMethodError","message":"undefined method `include?' for nil:NilClass","backtrace":["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-cef-6.2.5-java/lib/logstash/codecs/cef.rb:241:in `handle'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-cef-6.2.5-java/lib/logstash/codecs/cef.rb:197:in `block in decode'","org/jruby/RubyArray.java:1821:in `each'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-cef-6.2.5-java/lib/logstash/codecs/cef.rb:196:in `decode'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-tcp-6.3.0-java/lib/logstash/inputs/tcp.rb:194:in `decode_buffer'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-tcp-6.3.0-java/lib/logstash/inputs/tcp/decoder_impl.rb:22:in `decode'"],"original_data":"1245"}}}}}
```

**Comment by mashhurs** [comment]
Upgrade to v6.2.7 version.
